name: Build and Test Addon

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hererocks
        hererocks lua_install -r^ --lua=5.1
        source ./lua_install/bin/activate
        luarocks install argparse
        luarocks install luacheck
        luarocks install mockagne 1.0
        luarocks install luaunit
        luarocks install luabitop
        luarocks install busted
        luarocks install luacov
        luarocks install luacov-coveralls
        luarocks install luadoc
        luarocks list
    - name: Test with pytest
      run: |
        source ./lua_install/bin/activate
        luacheck --no-max-line-length --no-global --no-unused --allow-defined --std max+busted Localization.lua
        luacheck --no-max-line-length --no-global --no-unused --allow-defined --std max+busted RollTrackerClassicZ.lua
